---
- hosts: all
  gather_facts: True
  tasks:
  - name: add redis group
    group:
        name: redis
        state: present
  - name: add redis user 
    user:
        name: redis
        state: present
        append: yes
        group: redis
        createhome: yes
    
- name: codis environment init
  hosts: redis
  vars:
    - redis_bind: "{{ ansible_default_ipv4.address }}"
    - redis_user: redis
  roles:
    - redis
