---
- hosts: all
  gather_facts: True
  tasks:
  - name: set base facts
    set_fact:
      dashboard_addr: "{{ hostvars[groups['codis-dashboard-servers'][0]].ansible_default_ipv4.address }}:{{ dashboard_port }}"
  - name: add redis group
    group:
        name: redis
        state: present
  - name: add redis user 
    user:
        name: redis
        state: present
        append: yes
        group: redis
        createhome: yes
    
- name: codis environment init
  hosts: redis
  vars:
    - redis_bind: "{{ ansible_default_ipv4.address }}"
  roles:
    - redis
