---
- hosts: all
  gather_facts: True
  tasks:
  - name: add redis group
    group:
        name: redis
        state: present
  - name: add redis user 
    user:
        name: redis
        state: present
        append: yes
        group: redis
        createhome: yes

- name: set base facts
  hosts: redis
  tasks:
  - set_fact:
      redis_interface: "{{ ansible_default_ipv4.address }}"
      #redis_bind: "{{ ansible_default_ipv4.address }}"
      redis_bind1: 0.0.0.0
      redis_port: 6379
      redis_user: redis
      twemproxy_stats_addr: "{{ ansible_default_ipv4.address }}"

- name: install redis
  hosts: redis
  roles:
    - redis

 
- name: install twproxy
  hosts: redis
  vars:
    - twemproxy_pools:
        redis:
          listen: 0.0.0.0:6380
          hash: murmur
          distribution: modula
          auto_eject_hosts: "true"
          redis: "true"
          server_retry_timeout: 30000
          server_failure_limit: 1
          servers:
            group: redis
  roles:
    - twemproxy
