---
- hosts: all
  gather_facts: True
  tasks:
  - name: add redis group
    group:
        name: redis
        state: present
  - name: add redis user 
    user:
        name: redis
        state: present
        append: yes
        group: redis
        createhome: yes

- name: set base facts
  hosts: redis
  tasks:
  - set_fact:
      redis_interface: "{{ ansible_default_ipv4.address }}"
      #redis_bind: "{{ ansible_default_ipv4.address }}"
      redis_bind1: 0.0.0.0
      redis_port: 6379
      redis_user: redis
      twemproxy_stats_addr: "{{ ansible_default_ipv4.address }}"

- name: install redis
  hosts: redis
  roles:
    - redis-cluster

- name: install redis gem
  hosts: redis
  tasks:
    - gem:
        name: "{{ item }}"
        state: latest
      with_items:
        - "gem-path"
        - "redis"
    - command: "find / -name 'redis-trib.rb'"
      name: get redis path
      become: true
      register: gem_path_find
    
    - set_fact: 
        redis_trib_path: "{{ gem_path_find.stdout_lines[0] }}"
    
    - name: link redis-trib.rb
      command: "ln {{ redis_trib_path }} /usr/bin/redis-trib.rb"
      when: gem_path_find.stdout_lines|length == 1
      become: true

      


 
# - name: join nodes
#   hosts: redis[0]
#   tasks:
#     - gem:
#         name: redis
#         state: latest

#     - command: "redis-cli -h {{ ansible_default_ipv4.address }} -p {{ redis_port}} CLUSTER MEET {{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].redis_port }}  "
#       name: Exec redis-cli
#       with_items: "{{ groups.redis[1:] }}"

# - name: create slots
#   hosts: redis[0]
#   tasks:
#     - command: "redis-cli -h {{ ansible_default_ipv4.address }} -p {{ redis_port}} cluster info | grep cluster_slots_assigned: | awk -F':' '{print $2}'"
#       name: count slots
#       register: slots

#     - shell: "for slot in {0..16383}; do redis-cli -h {{ ansible_default_ipv4.address }} -p {{ redis_port}} CLUSTER ADDSLOTS $slot ; done;"
#       name: Exec redis-cli add slots
#       when: slots.stdout != "16384"
      

