---

dependencies: []

galaxy_info:
  author: Michel Blanc
  company: ACME Corp
  description: nutcracker/twemproxy role
  license: MIT
  min_ansible_version: 1.6
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - web
